---
controller_credential_types:
  - name: "AAP API Key"
    description: ""
    kind: "cloud"
    inputs:
      fields:
      - id: aap_api_key
        label: API Key
        secret: true
        type: string

    injectors:
      extra_vars:
        aap_api_key: !unsafe '{{aap_api_key}}'
  - name: "Github PAT"
    description: "Github Private Access Token"
    kind: "cloud"
    inputs:
      fields:
      - id: git_pat
        label: Github PAT
        secret: true
        type: string

    injectors:
      extra_vars:
        git_pat: !unsafe '{{git_pat}}'
  - name: "Username/password"
    description: ""
    kind: "cloud"
    inputs:
      fields:
      - id: username
        label: Username
        secret: false
        type: string
      - id: password
        label: password
        secret: true
        type: string

    injectors:
      extra_vars:
        password: !unsafe '{{password}}'
        username: !unsafe '{{username}}'
...
