---
- name: Output Automation Controller Configs
  hosts: aap-dev
  gather_facts: false
  vars:
    aap_username: "rriley"
    aap_password: ""
    aap_hostname: "192.168.122.124"
    aap_validate_certs: "false"
    controller_validate_certs: "false"
    output_path: "/home/rriley/ansible/CaC/group_vars/all"
    flatten_output: true

  pre_tasks:
    - name: "Setup authentication (block)"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      
        - name: Recursively remove output directory
          ansible.builtin.file:
            path: "{{ output_path }}"
            state: absent

  roles:
    - infra.aap_configuration_extended.filetree_create

...
