---
- name: Test
  hosts: aap-dev
  gather_facts: false

  tasks:
    - name: Git Login [username]
      ansible.builtin.command: "git config --global user.name \"rpriley5\""
      args:
        chdir: "/home/{{ ansible_user }}/ansible/CaC"
      changed_when: true

    - name: Git stage
      ansible.builtin.command: "git add ."
      args:
        chdir: "/home/{{ ansible_user }}/ansible/CaC"
      changed_when: true

    - name: Git commit
      ansible.builtin.command: "git commit -m \"auto-commit by AAP\""
      args:
        chdir: "/home/{{ ansible_user }}/ansible/CaC"
      changed_when: true

    - name: Git push
      ansible.builtin.command: "git push origin main"
      args:
        chdir: "/home/{{ ansible_user }}/ansible/CaC"
      changed_when: true
